"""Best-effort importer for simple ZPL created by Zebra Label Tool."""

from __future__ import annotations

from dataclasses import dataclass, field
import re

SUPPORTED_ALIGN_CODES = {"L": "left", "C": "center", "R": "right", "J": "justify"}
SUPPORTED_ROT_CODES = {"N": "normal", "R": "90", "I": "180", "B": "270"}


@dataclass(frozen=True)
class ImportedZplLabel:
    text_lines: tuple[str, ...] = field(default_factory=lambda: ("",))
    width_mm: float | None = None
    height_mm: float | None = None
    copies: int = 1
    inverted: bool = False
    border: bool = False
    barcode: bool = False
    barcode_text: str = ""
    barcode_pos: str = "below"
    font_size: int | None = None
    font_style: str = "A0"
    alignment: str = "center"
    rotation: str = "normal"
    line_gap: int = 10

    @property
    def line1(self) -> str:
        return self.text_lines[0] if self.text_lines else ""

    @property
    def line2(self) -> str:
        return self.text_lines[1] if len(self.text_lines) > 1 else ""


def _dots_to_mm(dots: int, dpi: int) -> float:
    return round(dots * 25.4 / dpi, 1)


def _extract_text_payload(zpl: str) -> tuple[str, ...]:
    matches = re.findall(r"\^FD(.*?)\^FS", zpl, flags=re.DOTALL)
    if not matches:
        return ("",)

    text_payload = matches[0].replace("^FR", "")
    return tuple(text_payload.replace("\\&", "\n").split("\n")) or ("",)


def parse_simple_zpl(zpl: str, dpi: int = 300) -> ImportedZplLabel:
    """Parse the simple ZPL shape generated by this project.

    This is intentionally not a full ZPL parser. It recovers the common fields from
    labels generated by this tool and ignores unsupported commands.
    """
    width_match = re.search(r"\^PW(\d+)", zpl)
    height_match = re.search(r"\^LL(\d+)", zpl)
    copies_match = re.search(r"\^PQ(\d+)", zpl)
    font_match = re.search(r"\^([A-Z0-9]+)([NRIB]),(\d+),(\d+)", zpl)
    fb_match = re.search(r"\^FB\d+,(\d+),(\d+),([LCRJ]),", zpl)

    text_lines = _extract_text_payload(zpl)

    barcode_match = re.search(r"\^BCN,\d+,Y,N,N\s*\^FD(.*?)\^FS", zpl, flags=re.DOTALL)
    barcode_text = barcode_match.group(1).strip() if barcode_match else ""

    text_pos = re.search(r"\^FO\d+,(\d+)\s*\n\^[A-Z0-9]+[NRIB],", zpl)
    barcode_pos = "below"
    if barcode_match and text_pos:
        barcode_fo = re.search(r"\^FO\d+,(\d+)\s*\n\^BCN", zpl)
        if barcode_fo and int(barcode_fo.group(1)) < int(text_pos.group(1)):
            barcode_pos = "above"

    return ImportedZplLabel(
        text_lines=text_lines,
        width_mm=_dots_to_mm(int(width_match.group(1)), dpi) if width_match else None,
        height_mm=_dots_to_mm(int(height_match.group(1)), dpi) if height_match else None,
        copies=int(copies_match.group(1)) if copies_match else 1,
        inverted="^FR^FD" in zpl or "^FO0,0^GB" in zpl,
        border=bool(re.search(r"\^FO2,2\^GB", zpl)),
        barcode=bool(barcode_match),
        barcode_text=barcode_text,
        barcode_pos=barcode_pos,
        font_size=int(font_match.group(3)) if font_match else None,
        font_style=font_match.group(1) if font_match else "A0",
        rotation=SUPPORTED_ROT_CODES.get(font_match.group(2), "normal") if font_match else "normal",
        alignment=SUPPORTED_ALIGN_CODES.get(fb_match.group(3), "center") if fb_match else "center",
        line_gap=int(fb_match.group(2)) if fb_match else 10,
    )
