"""Best-effort importer for simple ZPL created by Zebra Label Tool."""

from __future__ import annotations

from dataclasses import dataclass
import re

from .layout import mm_to_dots


@dataclass(frozen=True)
class ImportedZplLabel:
    line1: str = ""
    line2: str = ""
    width_mm: float | None = None
    height_mm: float | None = None
    copies: int = 1
    inverted: bool = False
    border: bool = False
    barcode: bool = False
    barcode_text: str = ""
    barcode_pos: str = "below"
    font_size: int | None = None
    font_style: str = "A0"


def _dots_to_mm(dots: int, dpi: int) -> float:
    return round(dots * 25.4 / dpi, 1)


def _extract_text_payload(zpl: str) -> tuple[str, str]:
    matches = re.findall(r"\^FD(.*?)\^FS", zpl, flags=re.DOTALL)
    if not matches:
        return "", ""

    # The generated text payload is the first ^FD block unless that block is clearly a barcode value.
    text_payload = matches[0].replace("^FR", "")
    text_payload = text_payload.replace("\\&", "\n")
    parts = text_payload.split("\n", 1)
    line1 = parts[0]
    line2 = parts[1] if len(parts) > 1 else ""
    return line1, line2


def parse_simple_zpl(zpl: str, dpi: int = 300) -> ImportedZplLabel:
    """Parse the simple ZPL shape generated by this project.

    This is intentionally not a full ZPL parser. It recovers the common fields from
    labels generated by this tool and ignores unsupported commands.
    """
    width_match = re.search(r"\^PW(\d+)", zpl)
    height_match = re.search(r"\^LL(\d+)", zpl)
    copies_match = re.search(r"\^PQ(\d+)", zpl)
    font_match = re.search(r"\^([A-Z0-9]+)N,(\d+),(\d+)", zpl)

    line1, line2 = _extract_text_payload(zpl)

    barcode_match = re.search(r"\^BCN,\d+,Y,N,N\s*\^FD(.*?)\^FS", zpl, flags=re.DOTALL)
    barcode_text = barcode_match.group(1).strip() if barcode_match else ""

    text_pos = re.search(r"\^FO\d+,(\d+)\s*\n\^[A-Z0-9]+N,", zpl)
    barcode_pos = "below"
    if barcode_match and text_pos:
        # Compare first barcode ^FO against text ^FO where possible.
        barcode_fo = re.search(r"\^FO\d+,(\d+)\s*\n\^BCN", zpl)
        if barcode_fo and int(barcode_fo.group(1)) < int(text_pos.group(1)):
            barcode_pos = "above"

    return ImportedZplLabel(
        line1=line1,
        line2=line2,
        width_mm=_dots_to_mm(int(width_match.group(1)), dpi) if width_match else None,
        height_mm=_dots_to_mm(int(height_match.group(1)), dpi) if height_match else None,
        copies=int(copies_match.group(1)) if copies_match else 1,
        inverted="^FR^FD" in zpl or "^FO0,0^GB" in zpl,
        border=bool(re.search(r"\^FO2,2\^GB", zpl)),
        barcode=bool(barcode_match),
        barcode_text=barcode_text,
        barcode_pos=barcode_pos,
        font_size=int(font_match.group(2)) if font_match else None,
        font_style=font_match.group(1) if font_match else "A0",
    )
